version: '3.9'

services:
  postgres:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: wallet-api
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "9090:8080"